spring:
  application:
    name: yahoo-stock-api-service
  webflux:
    base-path: /yahoo-stock-api
  codec:
    max-in-memory-size: 10MB
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10s
logging:
  level:
    reactivefeign.client.log: TRACE
feign-services:
  yahoo-endpoint: "https://query1.finance.yahoo.com/v10/finance/quoteSummary"
  nyse-endpoint: "https://www.nyse.com/api"
