spring:
  application:
    name: yahoo-stock-api-service
  webflux:
    base-path: /yahoo-stock-api
  codec:
    max-in-memory-size: 10MB
  cache:
    type: redis
  redis:
    port: 6379
    host: localhost
management:
  endpoints:
    web:
      exposure:
        include: caches, metrics
caching:
  cacheNames:
    marketData:
      ttl: 5 # in seconds
    baseInfo:
      ttl: 86400 # 1 day
    tickers:
      ttl: 86400 # 1 day
    returnCapital:
      ttl: 86400 # 1 day
    dividends:
      ttl: 86400 # 1 day
    historyDividends:
      ttl: 86400 # 1 day
logging:
  level:
    reactivefeign.client.log: DEBUG
feign-services:
  yahoo-endpoint: "https://query1.finance.yahoo.com/v10/finance/quoteSummary"
  nasdaq-endpoint: "https://api.nasdaq.com/api/quote"
  stock-analysis-api-endpoint: "https://api.stockanalysis.com"
  stock-analysis-endpoint: "https://stockanalysis.com"
