apiVersion: apps/v1
kind: Deployment
metadata:
  name: yahoo-stock-api-deployment
  namespace: intraday-traiding
  labels:
    app: yahoo-stock-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yahoo-stock-api
  template:
    metadata:
      labels:
        app: yahoo-stock-api
        visualize: "true"
    spec:
      containers:
        - name: yahoo-stock-api-pod
          image: dankosik/yahoo-stock-api
          ports:
            - containerPort: 8080
          env:
            - name: spring.webflux.base-path
              value: /yahoo-stock-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: intraday-traiding
  labels:
    visualize: "true"
  name: yahoo-stock-api-service
spec:
  selector:
    app: yahoo-stock-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080